home:
  label: "charging_dock"
  frame_id: "map"
  x: -0.003
  y: -0.019
  yaw: 0.003
  tolerance_xy: 0.25
  tolerance_yaw: 0.25
  notes: "stable home pose on lab_map_v2"

blue:
  label: "blue_bin"
  frame_id: "map"
  x: 6.801
  y: -2.931
  yaw: 3.107
  tolerance_xy: 0.25
  tolerance_yaw: 0.25
  notes: "blue target on lab_map_v2"

black:
  label: "black_bin"
  frame_id: "map"
  x: 12.932
  y: -0.660
  yaw: 2.280
  tolerance_xy: 0.25
  tolerance_yaw: 0.25
  notes: "black target on lab_map_v2"
